#pragma once
#include <pgmspace.h>

// Tag maintenance UI contract (all endpoints require the existing Digest admin
// authentication). GET /api/admin returns {configured,csrf}; use csrf as the
// X-BinRange-CSRF header for mutations. GET /api/tag-updates returns hostname,
// disabled, error, active_job_id, staging{capacity,available,version,size,
// file_sha256,image_hash}, tags{id,name,hardware_id,paired,address,address_type},
// jobs{id,tag,name,phase,acknowledged,size,attempts,error,version,image_hash,
// observed_version,observed_hash,confirmed,changed_ms}, and pairing{phase,error}.
// Mutations are POST /api/tag-updates/{pair,release,queue,
// cancel,retry} and POST /api/admin/password. Responses are 204 or JSON on
// success and text or {error} on failure; the browser must never retry them.
static const char UPDATE_PAGE[] PROGMEM = R"HTML(
<!doctype html><html lang=en><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>Tag maintenance</title>
<style>
:root{color-scheme:light dark;--bg:#f4f6fa;--fg:#19202b;--muted:#596579;--line:#c9d1dc;--panel:#fff;--input:#fff;--accent:#276ad9;--ok:#167744;--warn:#9a6200;--bad:#bc3434;--soft:#e9eef6}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.45 system-ui,sans-serif}.wrap{max-width:880px;margin:auto;padding:16px}.top{display:flex;justify-content:space-between;gap:12px;align-items:baseline;border-bottom:1px solid var(--line);padding:0 0 12px;margin-bottom:12px}h1{font-size:20px;margin:0}h2{font-size:15px;margin:0 0 10px}.host{color:var(--muted);font-size:13px}.notice,.status{padding:9px 11px;border-left:3px solid var(--accent);background:var(--soft);margin:0 0 12px}.status[hidden]{display:none}.status.bad{border-color:var(--bad)}.status.warn{border-color:var(--warn)}.stale{color:var(--warn)}section{border-top:1px solid var(--line);padding:15px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 14px}.wide{grid-column:1/-1}label{display:block;font-size:12px;font-weight:600;margin:0 0 4px}input,select,button,textarea{font:inherit;color:var(--fg);background:var(--input);border:1px solid var(--line);border-radius:6px;padding:8px;width:100%}textarea{min-height:92px;resize:vertical}input:focus,select:focus,textarea:focus,button:focus{outline:3px solid color-mix(in srgb,var(--accent) 35%,transparent);outline-offset:2px}button{width:auto;cursor:pointer;border-color:var(--accent);color:var(--accent);font-weight:600;white-space:nowrap}button.primary{background:var(--accent);color:#fff}button.danger{border-color:var(--bad);color:var(--bad)}button:disabled{opacity:.55;cursor:wait}.actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:11px}.hint,.meta{color:var(--muted);font-size:12px;margin:7px 0 0}.mono,.hash{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.hash{overflow-wrap:anywhere}.list{display:grid;gap:8px}.row{border:1px solid var(--line);border-radius:7px;padding:10px}.rowhead{display:flex;justify-content:space-between;gap:10px;align-items:baseline}.name{font-weight:700}.pill{font-size:12px;padding:2px 7px;border-radius:99px;background:var(--soft);color:var(--muted);white-space:nowrap}.successful{color:var(--ok)}.failed,.cancelled{color:var(--bad)}.needs_release,.needs_action{color:var(--warn)}.kv{display:grid;grid-template-columns:auto 1fr;gap:3px 10px;font-size:12px;margin-top:8px}.kv dt{color:var(--muted)}.empty{color:var(--muted);padding:8px 0}a{color:var(--accent)}@media (prefers-color-scheme:dark){:root{--bg:#0f1115;--fg:#e6e8ee;--muted:#9ba6b8;--line:#303846;--panel:#171a21;--input:#10141b;--accent:#76a9ff;--ok:#55d88c;--warn:#f1b957;--bad:#ff7b72;--soft:#1c2430}}@media(max-width:560px){.wrap{padding:12px}.top{align-items:flex-start;flex-direction:column;gap:4px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.rowhead{align-items:flex-start;flex-direction:column;gap:4px}.kv{grid-template-columns:1fr;gap:1px}.kv dd{margin:0 0 5px}}
</style>
<main class=wrap>
<header class=top><div><h1>Tag maintenance</h1><div id=host class=host>Connecting to controller</div></div><a href=/ aria-label="Open controller diagnostics">Diagnostics</a></header>
<p class=notice>For a trusted LAN only. Firmware images and pairing credentials can control nearby tags.</p>
<div id=liveStatus class=status role=status aria-live=polite>Loading admin status</div>
<div id=feedback class=status role=status aria-live=polite hidden><span id=feedbackText></span> <button id=dismissFeedback type=button>Dismiss</button></div>

<section><h2>Pair a tag</h2><div class=grid>
<div><label for=tag>Known tag</label><select id=tag><option value="">Choose a tag</option></select></div>
<div><label for=address>BLE address</label><input id=address autocomplete=off spellcheck=false placeholder="AA:BB:CC:DD:EE:FF"></div>
<div><label for=addressType>Address type</label><select id=addressType><option value=0>Public</option><option value=1>Random</option></select></div>
<div><label for=hardwareId>Expected hardware ID</label><input id=hardwareId autocomplete=off spellcheck=false></div>
<div><label for=pin>Six-digit pairing PIN</label><input id=pin type=password inputmode=numeric pattern="[0-9]{6}" maxlength=6 autocomplete=off></div>
</div><p id=selectedTag class=hint>Select a known tag to fill its saved identity, then enter the observed address and write-only PIN.</p><div class=actions><button id=pair type=button>Pair selected tag</button></div></section>

<section><h2>Staged release</h2><div id=staging class=meta>Release metadata unavailable</div><div class=grid style="margin-top:10px"><div class=wide><label for=manifest>Signed manifest JSON</label><textarea id=manifest spellcheck=false aria-describedby=releaseHelp></textarea></div><div class=wide><label for=image>Signed BIN image</label><input id=image type=file accept=.bin,application/octet-stream></div></div><p id=releaseHelp class=hint>The manifest and image are sent together. Upload does not queue any tag.</p><div class=actions><button id=release class=primary type=button>Stage release</button></div></section>

<section><h2>Queue update</h2><p id=queueTarget class=hint>Choose a tag after a release is staged.</p><div class=actions><button id=queue class=primary type=button>Queue selected tag</button></div></section>

<section><h2>Tag inventory</h2><div id=tags class=list aria-live=polite></div></section>
<section><h2>Update jobs</h2><div id=pairing class=meta></div><div id=jobs class=list aria-live=polite></div><button id=reconnect type=button hidden>Reconnect</button></section>

<section><h2>Change password and restart</h2><div class=grid><div><label for=password>New admin password</label><input id=password type=password autocomplete=new-password></div><div><label for=confirm>Password confirmation</label><input id=confirm type=password autocomplete=new-password></div></div><p class=hint>The controller will issue a fresh Digest challenge and restart. Reconnect with the new password.</p><div class=actions><button id=changePassword type=button>Change password and restart</button></div></section>
</main>
<script>
(()=>{'use strict';
const $=id=>document.getElementById(id), text=(el,value)=>el.textContent=value==null||value===''?'unknown':String(value);
let csrf='',state=null,inflight=false,lastOK=0,offline=false,pollPaused=false,tagInventory='',jobNodes=new Map();
const busy=new Set(), phaseText={queued:'Queued',waiting:'Waiting',connecting:'Connecting',uploading:'Uploading',rebooting:'Rebooting',checking:'Checking outcome',successful:'Successful',failed:'Failed',cancelled:'Cancelled',needs_release:'Needs release',needs_action:'Needs action'};
function live(value,kind){const el=$('liveStatus');text(el,value);el.className='status '+(kind||'');el.hidden=!value}
function message(value,kind){const el=$('feedback');text($('feedbackText'),value);el.className='status '+(kind||'');el.hidden=!value}
function apiError(response,body){let detail='';try{const j=JSON.parse(body);detail=j.error||''}catch(e){}return 'Request failed ('+response.status+'): '+(detail||body.trim()||response.statusText||'Unknown error')}
async function request(path,body){
  const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),body instanceof FormData?60000:10000);
  const options={method:'POST',credentials:'same-origin',headers:{'X-BinRange-CSRF':csrf},signal:ctl.signal};
  if(body instanceof FormData)options.body=body;
  else{options.headers['Content-Type']='application/x-www-form-urlencoded;charset=UTF-8';options.body=body.toString()}
  try{
    const r=await fetch(path,options),raw=await r.text();
    if(!r.ok){if(r.status===403)csrf='';const err=Error(apiError(r,raw));err.status=r.status;throw err}
    return {status:r.status,raw};
  }catch(e){
    if(e.status)throw e;
    throw Error((e.name==='AbortError'?'Request timed out':'Network error')+'; outcome unknown; refresh before retrying.');
  }finally{clearTimeout(timer)}
}
async function submit(key,button,work){if(busy.has(key))return;busy.add(key);button.disabled=true;message('');try{await work()}catch(e){message(e.message,'bad')}finally{busy.delete(key);button.disabled=false}}
function selected(){return state&&state.tags.find(t=>t.id===$('tag').value)}
function showTag(){const tag=selected();if(!tag){text($('selectedTag'),'Select a known tag to fill its saved identity, then enter the observed address and write-only PIN.');return}$('hardwareId').value=tag.hardware_id||'';$('address').value=tag.address||'';$('addressType').value=tag.address_type==null?'0':String(tag.address_type);text($('selectedTag'),tag.name||tag.id+' · '+(tag.hardware_id||'hardware ID unknown'));renderQueue()}
function renderTags(){const box=$('tags');box.replaceChildren();const tags=state.tags||[];if(!tags.length){const e=document.createElement('p');e.className='empty';text(e,'No tags are configured.');box.append(e);return}for(const t of tags){const r=document.createElement('div'),head=document.createElement('div'),n=document.createElement('span'),p=document.createElement('span'),d=document.createElement('div');r.className='row';head.className='rowhead';n.className='name';text(n,t.name||t.id);p.className='pill';text(p,t.paired?'paired':'not paired');head.append(n,p);d.className='meta';text(d,'ID '+t.id+' · hardware '+(t.hardware_id||'unknown')+' · '+(t.address||'address unknown'));r.append(head,d);box.append(r)}}
function makeJob(j){const r=document.createElement('article'),head=document.createElement('div'),n=document.createElement('span'),p=document.createElement('span'),d=document.createElement('dl'),a=document.createElement('div'),note=document.createElement('span'),cancel=document.createElement('button'),retry=document.createElement('button'),fields={};r.className='row';head.className='rowhead';n.className='name';p.className='pill';head.append(n,p);d.className='kv';for(const k of ['Job','Release','Image hash','Uploaded','Attempts','Observed version','Observed hash','Confirmed','Changed uptime','Error']){const dt=document.createElement('dt'),dd=document.createElement('dd');text(dt,k);if(k.includes('hash'))dd.className='hash';d.append(dt,dd);fields[k]=dd}a.className='actions';note.className='hint';cancel.className='danger';cancel.addEventListener('click',()=>submit(j.id+':cancel',cancel,async()=>{const current=jobNodes.get(j.id).job;await request('/api/tag-updates/cancel',new URLSearchParams({id:current.id}));message('Cancellation requested; wait for the reported outcome.');poll()}));retry.addEventListener('click',()=>submit(j.id+':retry',retry,async()=>{const current=jobNodes.get(j.id).job;if(!confirm('Retry job '+current.id+' for '+(current.name||current.tag||'this tag')+'?'))return;await request('/api/tag-updates/retry',new URLSearchParams({id:current.id}));message('Retry requested.');poll()}));a.append(cancel,retry,note);r.append(head,d,a);return {r,n,p,fields,cancel,retry,note,job:j}}
function renderJobs(){const box=$('jobs'),jobs=state.jobs||[],seen=new Set();for(const j of jobs){seen.add(j.id);let entry=jobNodes.get(j.id);if(!entry){entry=makeJob(j);jobNodes.set(j.id,entry)}entry.job=j;text(entry.n,j.name||j.tag||j.id);entry.p.className='pill '+(j.phase||'');text(entry.p,phaseText[j.phase]||j.phase||'unknown');const values={Job:j.id,Release:j.version,'Image hash':j.image_hash,Uploaded:j.acknowledged==null?'unknown':j.acknowledged+'/'+(j.size==null?'unknown':j.size),Attempts:j.attempts,'Observed version':j.observed_version,'Observed hash':j.observed_hash,Confirmed:j.confirmed===true?'yes':j.confirmed===false?'no':'unknown','Changed uptime':j.changed_ms==null?'unknown':j.changed_ms+' ms',Error:j.error||"none"};for(const k in values)text(entry.fields[k],values[k]);const beforeTrial=['queued','waiting','connecting','uploading'].includes(j.phase),uncertain=['rebooting','checking'].includes(j.phase),retryable=['needs_release','needs_action'].includes(j.phase);entry.cancel.hidden=!beforeTrial&&!uncertain;entry.retry.hidden=!retryable;text(entry.cancel,beforeTrial?'Cancel before trial':'Stop transfer / check outcome');entry.note.textContent=uncertain?'An armed trial cannot be undone; wait for its outcome.':'';if(entry.r.parentNode!==box)box.append(entry.r)}for(const [id,entry] of jobNodes){if(!seen.has(id)){entry.r.remove();jobNodes.delete(id)}}if(!jobs.length){let e=$('jobsEmpty');if(!e){e=document.createElement('p');e.id='jobsEmpty';e.className='empty';text(e,'No update jobs.');box.append(e)}}else{const e=$('jobsEmpty');if(e)e.remove()}}
function renderQueue(){const tag=selected(),st=state&&state.staging;if(!tag){text($('queueTarget'),'Choose a tag after a release is staged.');return}text($('queueTarget'),'Target: '+(tag.name||tag.id)+' · hardware '+(tag.hardware_id||'unknown')+(st&&st.version?' · release '+st.version:' · no staged release'))}
function render(){text($('host'),state.hostname||'Controller hostname unknown');const st=state.staging||{},parts=[st.available===true?'Staged release available':st.available===false?'No release staged':'Release availability unknown','Capacity '+(st.capacity==null?'unknown':st.capacity+' bytes')];if(st.version)parts.push('Release '+st.version);if(st.size!=null)parts.push('Image '+st.size+' bytes');if(st.file_sha256)parts.push('File '+st.file_sha256);if(st.image_hash)parts.push('Image hash '+st.image_hash);text($('staging'),parts.join(' · '));$('staging').className='meta hash';const inventory=(state.tags||[]).map(t=>[t.id,t.name,t.hardware_id].join('\u001f')).join('\u001e');if(inventory!==tagInventory){const prior=$('tag').value,sel=$('tag');sel.replaceChildren();const blank=document.createElement('option');blank.value='';text(blank,'Choose a tag');sel.append(blank);for(const t of state.tags||[]){const o=document.createElement('option');o.value=t.id;text(o,(t.name||'Unnamed tag')+' · UWB '+t.id+' · '+(t.hardware_id||'hardware ID unknown'));sel.append(o)}sel.value=prior;tagInventory=inventory}renderTags();renderQueue();renderJobs();const pairing=state.pairing||{};text($('pairing'),pairing.phase?('Pairing: '+pairing.phase+(pairing.error?' · '+pairing.error:'')):'');if(state.disabled)live(state.error||'Tag updates are unavailable.','bad');else if(!offline)live('Live status · updated just now.','')}
async function poll(){if(inflight||pollPaused)return;inflight=true;const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),4000);try{if(!csrf){const a=await fetch('/api/admin',{credentials:'same-origin',signal:ctl.signal});const raw=await a.text();if(!a.ok){const err=Error(apiError(a,raw));err.status=a.status;throw err}csrf=JSON.parse(raw).csrf||'';if(!csrf)throw Error('Admin CSRF token unavailable.')}const r=await fetch('/api/tag-updates',{credentials:'same-origin',signal:ctl.signal}),raw=await r.text();if(!r.ok){const err=Error(apiError(r,raw));err.status=r.status;throw err}state=JSON.parse(raw);lastOK=Date.now();offline=false;render()}catch(e){offline=true;if(e.status===401){pollPaused=true;$('reconnect').hidden=false;live('Authentication required. Polling paused; reconnect to continue.','warn')}else{const age=lastOK?Math.round((Date.now()-lastOK)/1000)+' s ago':'never';live('Status offline or stale; last live update '+age+'. '+e.message,'warn')}}finally{clearTimeout(timer);inflight=false}}
$('tag').addEventListener('change',showTag);
$('dismissFeedback').addEventListener('click',()=>message(''));
$('reconnect').addEventListener('click',()=>{csrf='';pollPaused=false;$('reconnect').hidden=true;live('Reconnecting.');poll()});
$('pair').addEventListener('click',()=>submit('pair',$('pair'),async()=>{const tag=selected();if(!tag)throw Error('Choose a known tag.');const pin=$('pin').value;if(!/^\d{6}$/.test(pin))throw Error('Enter a six-digit pairing PIN.');if(!confirm('Pair '+(tag.name||tag.id)+' with hardware '+($('hardwareId').value||'unknown')+'?'))return;try{await request('/api/tag-updates/pair',new URLSearchParams({tag:tag.id,address:$('address').value,address_type:$('addressType').value,hardware_id:$('hardwareId').value,pin}));message('Pairing requested.');poll()}finally{$('pin').value=''}}));
$('release').addEventListener('click',()=>submit('release',$('release'),async()=>{const file=$('image').files[0],manifest=$('manifest').value;if(!file)throw Error('Choose a signed BIN image.');try{JSON.parse(manifest)}catch(e){throw Error('Manifest must be valid JSON.')}const form=new FormData();form.append('manifest',manifest);form.append('file',file);await request('/api/tag-updates/release',form);$('image').value='';message('Release staged.');poll()}));
$('queue').addEventListener('click',()=>submit('queue',$('queue'),async()=>{const tag=selected(),st=state&&state.staging;if(!tag)throw Error('Choose a tag.');if(!st||!st.version)throw Error('Stage a release before queueing.');const target=(tag.name||tag.id)+' / '+(tag.hardware_id||'unknown')+' / release '+st.version;if(!confirm('Queue update for '+target+'?'))return;await request('/api/tag-updates/queue',new URLSearchParams({tag:tag.id}));message('Update queued for '+(tag.name||tag.id)+'.');poll()}));
$('changePassword').addEventListener('click',()=>submit('password',$('changePassword'),async()=>{const pass=$('password').value,confirmPass=$('confirm').value;if(!pass||pass!==confirmPass){$('password').value='';$('confirm').value='';throw Error('Enter matching new passwords.')}if(!confirm('Change the admin password and restart this controller?'))return;try{const result=await request('/api/admin/password',new URLSearchParams({password:pass,confirm:confirmPass}));message(result.status===204?'Password unchanged.':'Password request completed; reconnect and verify.','')}catch(e){if(e.status===401)message('Authentication required; password may have changed—reconnect and verify.','warn');else throw e}finally{$('password').value='';$('confirm').value=''}}));
setInterval(poll,1000);poll();
})();
</script>
)HTML";
